 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Clases.Spot;
import Clases.Ticket;
import DAO.TicketDAO;
import Gestiones.GestionPAR;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author dcuyu
 */
public class Parqueos extends javax.swing.JDialog {
    GestionPAR gestionPAR = new GestionPAR();
    public  ArrayList<JToggleButton> espaciosMot = new ArrayList<>();
    public  ArrayList<JToggleButton> espaciosDoc = new ArrayList<>();
    public  ArrayList<JToggleButton> espaciosEst = new ArrayList<>();
    private Spot spotSeleccionadoGlobal = null;
    private String carnet;
    private String placa;
    private String tipoUsuario;
    private String tipoVehiculo;
    private String nombre;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Parqueos.class.getName());

    /**
     * Creates new form Parqueos
     */
    public Parqueos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        EspaciosM();
        EspaciosE();
        EspaciosD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbtnM1 = new javax.swing.JToggleButton();
        tbtnM2 = new javax.swing.JToggleButton();
        tbtnM3 = new javax.swing.JToggleButton();
        tbtnM4 = new javax.swing.JToggleButton();
        tbtnM5 = new javax.swing.JToggleButton();
        tbtnM6 = new javax.swing.JToggleButton();
        tbtnM7 = new javax.swing.JToggleButton();
        tbtnM8 = new javax.swing.JToggleButton();
        tbtnM9 = new javax.swing.JToggleButton();
        tbtnM10 = new javax.swing.JToggleButton();
        tbtnM21 = new javax.swing.JToggleButton();
        tbtnM22 = new javax.swing.JToggleButton();
        tbtnM23 = new javax.swing.JToggleButton();
        tbtnM24 = new javax.swing.JToggleButton();
        tbtnM25 = new javax.swing.JToggleButton();
        tbtnM26 = new javax.swing.JToggleButton();
        tbtnM27 = new javax.swing.JToggleButton();
        tbtnM28 = new javax.swing.JToggleButton();
        tbtnM29 = new javax.swing.JToggleButton();
        tbtnM30 = new javax.swing.JToggleButton();
        tbtnM11 = new javax.swing.JToggleButton();
        tbtnM12 = new javax.swing.JToggleButton();
        tbtnM13 = new javax.swing.JToggleButton();
        tbtnM14 = new javax.swing.JToggleButton();
        tbtnM15 = new javax.swing.JToggleButton();
        tbtnM16 = new javax.swing.JToggleButton();
        tbtnM17 = new javax.swing.JToggleButton();
        tbtnM18 = new javax.swing.JToggleButton();
        tbtnM19 = new javax.swing.JToggleButton();
        tbtnM20 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tbtnD1 = new javax.swing.JToggleButton();
        tbtnD2 = new javax.swing.JToggleButton();
        tbtnD3 = new javax.swing.JToggleButton();
        tbtnD4 = new javax.swing.JToggleButton();
        tbtnD7 = new javax.swing.JToggleButton();
        tbtnD10 = new javax.swing.JToggleButton();
        tbtnD5 = new javax.swing.JToggleButton();
        tbtnD6 = new javax.swing.JToggleButton();
        tbtnD8 = new javax.swing.JToggleButton();
        tbtnD9 = new javax.swing.JToggleButton();
        tbtnD12 = new javax.swing.JToggleButton();
        tbtnD11 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tbtnE1 = new javax.swing.JToggleButton();
        tbtnE11 = new javax.swing.JToggleButton();
        tbtnE16 = new javax.swing.JToggleButton();
        tbtnE12 = new javax.swing.JToggleButton();
        tbtnE17 = new javax.swing.JToggleButton();
        tbtnE2 = new javax.swing.JToggleButton();
        tbtnE7 = new javax.swing.JToggleButton();
        tbtnE13 = new javax.swing.JToggleButton();
        tbtnE18 = new javax.swing.JToggleButton();
        tbtnE8 = new javax.swing.JToggleButton();
        tbtnE6 = new javax.swing.JToggleButton();
        tbtnE3 = new javax.swing.JToggleButton();
        tbtnE4 = new javax.swing.JToggleButton();
        tbtnE5 = new javax.swing.JToggleButton();
        tbtnE9 = new javax.swing.JToggleButton();
        tbtnE10 = new javax.swing.JToggleButton();
        tbtnE14 = new javax.swing.JToggleButton();
        tbtnE15 = new javax.swing.JToggleButton();
        tbtnE19 = new javax.swing.JToggleButton();
        tbtnE20 = new javax.swing.JToggleButton();
        btnParquear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Motos");

        tbtnM1.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM1.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM1.setPreferredSize(new java.awt.Dimension(90, 50));
        tbtnM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnM1ActionPerformed(evt);
            }
        });

        tbtnM2.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM2.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM2.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM3.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM3.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM3.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM4.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM4.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM4.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM5.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM5.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM5.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM6.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM6.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM6.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM7.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM7.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM7.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM8.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM8.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM8.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM9.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM9.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM9.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM10.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM10.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM10.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM21.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM21.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM21.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM22.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM22.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM22.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM23.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM23.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM23.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM24.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM24.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM24.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM25.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM25.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM25.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM26.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM26.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM26.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM27.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM27.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM27.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM28.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM28.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM28.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM29.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM29.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM29.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM30.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM30.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM30.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM11.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM11.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM11.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM12.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM12.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM12.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM13.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM13.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM13.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM14.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM14.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM14.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM15.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM15.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM15.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM16.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM16.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM16.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM17.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM17.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM17.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM18.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM18.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM18.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM19.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM19.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM19.setPreferredSize(new java.awt.Dimension(90, 50));

        tbtnM20.setMaximumSize(new java.awt.Dimension(90, 50));
        tbtnM20.setMinimumSize(new java.awt.Dimension(90, 50));
        tbtnM20.setPreferredSize(new java.awt.Dimension(90, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnM11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnM21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbtnM30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnM19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnM29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tbtnM18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbtnM28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tbtnM11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tbtnM21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tbtnM27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(56, 56, 56)))
                                .addGap(56, 56, 56)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(tbtnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnM10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Docentes");

        tbtnD1.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD1.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD1.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD2.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD2.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD2.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD3.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD3.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD3.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD4.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD4.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD4.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD7.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD7.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD7.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD10.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD10.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD10.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD5.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD5.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD5.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD6.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD6.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD6.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD8.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD8.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD8.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD9.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD9.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD9.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD12.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD12.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD12.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnD11.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnD11.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnD11.setPreferredSize(new java.awt.Dimension(120, 60));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tbtnD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnD7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tbtnD5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnD8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tbtnD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnD9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnD10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnD11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnD12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tbtnD10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbtnD11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tbtnD7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbtnD8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbtnD5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtnD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnD9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnD12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Estudiantes");

        tbtnE1.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE1.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE1.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE11.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE11.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE11.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE16.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE16.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE16.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE12.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE12.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE12.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE17.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE17.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE17.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE2.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE2.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE2.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE7.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE7.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE7.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE13.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE13.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE13.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE18.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE18.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE18.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE8.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE8.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE8.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE6.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE6.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE6.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE3.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE3.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE3.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE4.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE4.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE4.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE5.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE5.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE5.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE9.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE9.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE9.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE10.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE10.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE10.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE14.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE14.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE14.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE15.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE15.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE15.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE19.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE19.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE19.setPreferredSize(new java.awt.Dimension(120, 60));

        tbtnE20.setMaximumSize(new java.awt.Dimension(120, 60));
        tbtnE20.setMinimumSize(new java.awt.Dimension(120, 60));
        tbtnE20.setPreferredSize(new java.awt.Dimension(120, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnE5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tbtnE6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnE11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnE16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tbtnE7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnE12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnE17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tbtnE8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnE13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnE18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tbtnE10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbtnE9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tbtnE15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbtnE14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tbtnE20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbtnE19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tbtnE14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnE15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tbtnE16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbtnE17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(tbtnE11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbtnE12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbtnE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbtnE6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtnE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbtnE7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnE8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnE13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnE18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tbtnE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtnE5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tbtnE9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtnE10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tbtnE19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnE20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnParquear.setText("Parquear");
        btnParquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParquearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnParquear)
                .addGap(406, 406, 406))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnParquear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private ArrayList<JToggleButton> EspaciosM(){
        espaciosMot.add(tbtnM1); espaciosMot.add(tbtnM2); espaciosMot.add(tbtnM3); espaciosMot.add(tbtnM4); espaciosMot.add(tbtnM5); espaciosMot.add(tbtnM6);
        espaciosMot.add(tbtnM7); espaciosMot.add(tbtnM8); espaciosMot.add(tbtnM9); espaciosMot.add(tbtnM10); espaciosMot.add(tbtnM11); espaciosMot.add(tbtnM12);
        espaciosMot.add(tbtnM13); espaciosMot.add(tbtnM14); espaciosMot.add(tbtnM15); espaciosMot.add(tbtnM16); espaciosMot.add(tbtnM17); espaciosMot.add(tbtnM18);
        espaciosMot.add(tbtnM19); espaciosMot.add(tbtnM20); espaciosMot.add(tbtnM21); espaciosMot.add(tbtnM22); espaciosMot.add(tbtnM23); espaciosMot.add(tbtnM24);
        espaciosMot.add(tbtnM25); espaciosMot.add(tbtnM26); espaciosMot.add(tbtnM27); espaciosMot.add(tbtnM28); espaciosMot.add(tbtnM29); espaciosMot.add(tbtnM30);
        return espaciosMot;
    }
    
    private ArrayList<JToggleButton> EspaciosD(){
        espaciosDoc.add(tbtnD1); espaciosDoc.add(tbtnD2); espaciosDoc.add(tbtnD3); espaciosDoc.add(tbtnD4); espaciosDoc.add(tbtnD5); espaciosDoc.add(tbtnD6);
        espaciosDoc.add(tbtnD7); espaciosDoc.add(tbtnD8); espaciosDoc.add(tbtnD9); espaciosDoc.add(tbtnD10); espaciosDoc.add(tbtnD11); espaciosDoc.add(tbtnD12);
        return espaciosDoc;
    }
    
    private ArrayList<JToggleButton> EspaciosE(){
        espaciosEst.add(tbtnE1); espaciosEst.add(tbtnE2); espaciosEst.add(tbtnE3); espaciosEst.add(tbtnE4); espaciosEst.add(tbtnE5); espaciosEst.add(tbtnE6);
        espaciosEst.add(tbtnE7); espaciosEst.add(tbtnE8); espaciosEst.add(tbtnE9); espaciosEst.add(tbtnE10); espaciosEst.add(tbtnE11); espaciosEst.add(tbtnE12);
        espaciosEst.add(tbtnE13); espaciosEst.add(tbtnE14); espaciosEst.add(tbtnE15); espaciosEst.add(tbtnE16); espaciosEst.add(tbtnE17); espaciosEst.add(tbtnE18);
        espaciosEst.add(tbtnE19); espaciosEst.add(tbtnE20);
        return espaciosEst;
    }
    
    public void crearGrupos(){
        ButtonGroup spots = new ButtonGroup();
            for (JToggleButton btn : espaciosEst) {
                spots.add(btn);
            }
            for (JToggleButton btn : espaciosDoc) {
                spots.add(btn);
            }        
            for (JToggleButton btn : espaciosMot) {
                spots.add(btn);
            }
    }
    
    public void cargarSpotsEnBotones(String tipoUsuario, String tipoVehiculo) {

        // 1. áreas en un mapa codigo -> nombre
        Map<String, String> mapaAreas = gestionPAR.obtenerNombreAreaPorCodigo();

        // 2. todos los spots desde BD
        List<Spot> spots = gestionPAR.obtenerTodosLosSpots();

        // índices para asignar botones correctamente
        int iMoto = 0;
        int iEst = 0;
        int iDoc = 0;

        // 🔥 Si es GESTION, bloquear botón parquear
        boolean esGestion = tipoUsuario.equalsIgnoreCase("GESTION") 
                            && tipoVehiculo.equalsIgnoreCase("GESTION");
        if (esGestion && btnParquear != null) {
            btnParquear.setEnabled(false);
        }

        for (Spot s : spots) {

            String areaNombre = mapaAreas.get(s.getCodigodearea());
            JToggleButton boton = null;

            switch (areaNombre) {
                case "MOTOS":
                    boton = espaciosMot.get(iMoto++);
                    break;

                case "ESTUDIANTES":
                    boton = espaciosEst.get(iEst++);
                    break;

                case "DOCENTES":
                    boton = espaciosDoc.get(iDoc++);
                    break;
            }

            if (boton != null) {

                // Mostrar info
                boton.setText("<html>" + s.getCodigo() + "<br>"
                        + s.getTipodevehiculo() + "<br>"
                        + (s.isEstado() ? "Ocupado" : "Libre") +
                        "</html>"
                );

                boton.putClientProperty("spot", s);

                boton.addActionListener(e -> spotSeleccionado(e));

                // -----------------------------------------
                // 🔥 Si es GESTION → NO bloquear ningún botón
                // -----------------------------------------
                if (esGestion) {
                    // Solo mostrar color normal por estado
                    if (s.isEstado()) {
                        boton.setBackground(Color.RED);
                        boton.setEnabled(false);
                        boton.setForeground(Color.BLACK);
                    } else {
                        boton.setBackground(Color.GREEN);
                        boton.setEnabled(false);
                        boton.setForeground(Color.BLACK);
                    }
                    continue; // ← ir al siguiente botón
                }

                // ---------- Lógica normal ----------
                boolean habilitar = true;

                if (s.isEstado()) habilitar = false;

                if (tipoVehiculo.equalsIgnoreCase("MOTO")) {
                    if (!areaNombre.equals("MOTOS")) habilitar = false;
                } 
                else if (tipoVehiculo.equalsIgnoreCase("CARRO")) {

                    if (tipoUsuario.equalsIgnoreCase("ESTUDIANTE")) {
                        if (!areaNombre.equals("ESTUDIANTES")) habilitar = false;
                    } 
                    else if (tipoUsuario.equalsIgnoreCase("DOCENTE") ||
                             tipoUsuario.equalsIgnoreCase("INVITADO")) {
                        if (!areaNombre.equals("ESTUDIANTES") &&
                            !areaNombre.equals("DOCENTES")) habilitar = false;
                    }
                }

                // Aplicar color
                if (!habilitar) {
                    boton.setBackground(Color.RED);
                    boton.setEnabled(false);
                    boton.setForeground(Color.BLACK);
                } else {
                    boton.setBackground(Color.GREEN);
                    boton.setEnabled(true);
                    boton.setForeground(Color.BLACK);
                }
            }
        }
    }

    
    private void spotSeleccionado(ActionEvent e) {
        JToggleButton btn = (JToggleButton) e.getSource();

        // Obtener el spot guardado en el botón
        Spot spot = (Spot) btn.getClientProperty("spot");

        // Guardarlo para usarlo luego
        spotSeleccionadoGlobal = spot;
    }

    public Spot getSpotSeleccionadoGlobal() {
        return spotSeleccionadoGlobal;
    }
    
    private void tbtnM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnM1ActionPerformed
        
    }//GEN-LAST:event_tbtnM1ActionPerformed

    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    
    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }
    
    public void setNombre(String nombre){
        this.nombre = nombre;
    }
    
    private void btnParquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParquearActionPerformed
    Spot spot = this.spotSeleccionadoGlobal;
        if (spot == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un spot.");
            return;
        }
        String carnet;
        String placa;
        String tipoUsuario;
        String tipoVehiculo;
        
        if ("INVITADO".equalsIgnoreCase(this.tipoUsuario)) {
         carnet = this.nombre;
         placa = this.tipoVehiculo;
         tipoUsuario = this.tipoUsuario;
         tipoVehiculo = this.tipoVehiculo;
        } else {
         carnet = this.carnet;
         placa = this.placa;
         tipoUsuario = this.tipoUsuario;
         tipoVehiculo = this.tipoVehiculo;
        }


    // ---------- PASO 1: ESCOGER TIPO DE TARIFA ----------
    String[] opciones = {"Tarifa Plana", "Tarifa Variable"};
    String tarifaSel = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione el tipo de tarifa:",
            "Tipo de Tarifa",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
    );
    if (tarifaSel == null) return; // cancelado



    Ticket t = new Ticket();
    t.setPlacaVehiculo(placa);
    t.setCarnetUsuario(carnet);
    t.setTipoUsuario(tipoUsuario);
    t.setTipoVehiculo(tipoVehiculo);
    t.setCodigoSpot(spot.getCodigo());
    t.setCodigoArea(spot.getCodigodearea());
    t.setFechaHoraIngreso(LocalDateTime.now());


    // ---------- PASO 2: TARIFA PLANA ----------
    if (tarifaSel.equals("Tarifa Plana")) {

        // método de pago
        String[] metodos = {"Efectivo", "Tarjeta", "Transferencia"};
        String metodoPago = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione método de pago:",
                "Método de Pago",
                JOptionPane.QUESTION_MESSAGE,
                null,
                metodos,
                metodos[0]
        );
        if (metodoPago == null) return;

        double montoFijo = 15.00;

        t.setTarifaAplicada("PLANA");
        t.setMonto(montoFijo);
        t.setMetodoPago(metodoPago);
        t.setEstado("ACTIVO");

    } 
    // ---------- PASO 3: TARIFA VARIABLE ----------
    else if (tarifaSel.equals("Tarifa Variable")) {

        t.setTarifaAplicada("VARIABLE");
        t.setMonto(0);
        t.setMetodoPago("PENDIENTE");
        t.setEstado("PENDIENTE");
    }



    // ---------- PASO 4: GUARDAR EN BD ----------
    TicketDAO dao = new TicketDAO();
    boolean ok = dao.insertarTicketYMarcarSpot(t, spot.getCodigo());

    if (!ok) {
        JOptionPane.showMessageDialog(this, "Error al registrar la entrada.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }  
    
    String resumen =
        "Ticket registrado\n\n" +
        "Ticket: " + t.getId() + "\n" +
        "Placa: " + t.getPlacaVehiculo() + "\n" +
        "Carnet: " + t.getCarnetUsuario() + "\n" +
        "Usuario: " + t.getTipoUsuario() + "\n" +
        "Vehículo: " + t.getTipoVehiculo() + "\n" +
        "Spot: " + t.getCodigoSpot() + "\n" +
        "Área: " + t.getCodigoArea() + "\n" +
        "Tarifa: " + t.getTarifaAplicada() + "\n" +
        "Monto: Q" + t.getMonto() + "\n" +
        "Método Pago: " + t.getMetodoPago() + "\n" +
        "Estado: " + t.getEstado() + "\n" +
        "Hora Ingreso: " + t.getFechaHoraIngreso().toString();

    JOptionPane.showMessageDialog(this, resumen, "Ticket Generado", JOptionPane.INFORMATION_MESSAGE);
    this.dispose();
        
    }//GEN-LAST:event_btnParquearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Parqueos dialog = new Parqueos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParquear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton tbtnD1;
    private javax.swing.JToggleButton tbtnD10;
    private javax.swing.JToggleButton tbtnD11;
    private javax.swing.JToggleButton tbtnD12;
    private javax.swing.JToggleButton tbtnD2;
    private javax.swing.JToggleButton tbtnD3;
    private javax.swing.JToggleButton tbtnD4;
    private javax.swing.JToggleButton tbtnD5;
    private javax.swing.JToggleButton tbtnD6;
    private javax.swing.JToggleButton tbtnD7;
    private javax.swing.JToggleButton tbtnD8;
    private javax.swing.JToggleButton tbtnD9;
    private javax.swing.JToggleButton tbtnE1;
    private javax.swing.JToggleButton tbtnE10;
    private javax.swing.JToggleButton tbtnE11;
    private javax.swing.JToggleButton tbtnE12;
    private javax.swing.JToggleButton tbtnE13;
    private javax.swing.JToggleButton tbtnE14;
    private javax.swing.JToggleButton tbtnE15;
    private javax.swing.JToggleButton tbtnE16;
    private javax.swing.JToggleButton tbtnE17;
    private javax.swing.JToggleButton tbtnE18;
    private javax.swing.JToggleButton tbtnE19;
    private javax.swing.JToggleButton tbtnE2;
    private javax.swing.JToggleButton tbtnE20;
    private javax.swing.JToggleButton tbtnE3;
    private javax.swing.JToggleButton tbtnE4;
    private javax.swing.JToggleButton tbtnE5;
    private javax.swing.JToggleButton tbtnE6;
    private javax.swing.JToggleButton tbtnE7;
    private javax.swing.JToggleButton tbtnE8;
    private javax.swing.JToggleButton tbtnE9;
    private javax.swing.JToggleButton tbtnM1;
    private javax.swing.JToggleButton tbtnM10;
    private javax.swing.JToggleButton tbtnM11;
    private javax.swing.JToggleButton tbtnM12;
    private javax.swing.JToggleButton tbtnM13;
    private javax.swing.JToggleButton tbtnM14;
    private javax.swing.JToggleButton tbtnM15;
    private javax.swing.JToggleButton tbtnM16;
    private javax.swing.JToggleButton tbtnM17;
    private javax.swing.JToggleButton tbtnM18;
    private javax.swing.JToggleButton tbtnM19;
    private javax.swing.JToggleButton tbtnM2;
    private javax.swing.JToggleButton tbtnM20;
    private javax.swing.JToggleButton tbtnM21;
    private javax.swing.JToggleButton tbtnM22;
    private javax.swing.JToggleButton tbtnM23;
    private javax.swing.JToggleButton tbtnM24;
    private javax.swing.JToggleButton tbtnM25;
    private javax.swing.JToggleButton tbtnM26;
    private javax.swing.JToggleButton tbtnM27;
    private javax.swing.JToggleButton tbtnM28;
    private javax.swing.JToggleButton tbtnM29;
    private javax.swing.JToggleButton tbtnM3;
    private javax.swing.JToggleButton tbtnM30;
    private javax.swing.JToggleButton tbtnM4;
    private javax.swing.JToggleButton tbtnM5;
    private javax.swing.JToggleButton tbtnM6;
    private javax.swing.JToggleButton tbtnM7;
    private javax.swing.JToggleButton tbtnM8;
    private javax.swing.JToggleButton tbtnM9;
    // End of variables declaration//GEN-END:variables
}
