/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Clases.Carro;
import Clases.Moto;
import Clases.UsuarioVehiculo;
import DAO.UsuarioDAO;
import DAO.UsuarioVehiculoDAO;
import DAO.VehiculoDAO;
import Gestiones.Gestion;
import com.mycompany.parkplus.PantallaPark;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author dcuyu
 */
public class Vehiculo extends javax.swing.JDialog {
    ArrayList<Clases.Vehiculo> vehiculo = new ArrayList<>();
    ArrayList<UsuarioVehiculo> uv = new ArrayList<>();
    ArrayList<Clases.Vehiculo> vehiculos = new ArrayList<>();
    Gestion gestion = new Gestion();
    VehiculoDAO daoV = new VehiculoDAO();
    UsuarioDAO daoU = new UsuarioDAO();
    UsuarioVehiculoDAO daoUV = new UsuarioVehiculoDAO();
    boolean vehiculoMinimo = false;
    private PantallaPark p;
    private String carnet;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vehiculo.class.getName());

    /**
     * Creates new form Vehiculo
     */
    public Vehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoVehiculo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        txtRol = new javax.swing.JComboBox<>();
        rbtnMoto = new javax.swing.JRadioButton();
        rbtnCarro = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Usuario:");

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CARNET", "TELEFONO", "NOMBRE", "APELLIDO", "TIPO", "CARRERA", "SEMESTRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuario);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Vehiculos a agregar:");

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PLACA", "COLOR", "TIPO DE VEHICULO", "ROL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaVehiculos);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Placa:");

        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaFocusLost(evt);
            }
        });
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        jLabel4.setText("Color:");

        txtRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Rol", "Propietario", "Tercero" }));

        tipoVehiculo.add(rbtnMoto);
        rbtnMoto.setText("Moto");

        tipoVehiculo.add(rbtnCarro);
        rbtnCarro.setText("Carro");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnMoto)
                    .addComponent(rbtnCarro)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String placa = txtPlaca.getText().toUpperCase().trim();
        String rol = txtRol.getSelectedItem().toString().toUpperCase().trim();
               
        if (!validarCamposv()) {
        JOptionPane.showMessageDialog(this, "Por favor llene todos los campos.");
        return;    
        }
        
        if (rol.equalsIgnoreCase("Propietario")) {
            if (daoUV.tienePropietario(placa)) {
                JOptionPane.showMessageDialog(this, "Este vehiculo ya tiene un propietario registrado.");
                return;
            }
        }
        
        String color = txtColor.getText().toUpperCase();
        String tipovehiculo;
        
        if (daoUV.existeRol(carnet, placa)) {
        JOptionPane.showMessageDialog(null, 
        "Error: La placa " + placa + " ya tiene un rol para este usuario.", 
        "Validación", 
        JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if (gestion.yaExisteVenLista(this.vehiculo, placa)) {
        JOptionPane.showMessageDialog(null, 
        "Error: La placa " + placa + " ya tiene un rol para este usuario.", 
        "Validación", 
        JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if (rbtnMoto.isSelected()) {
        tipovehiculo = "MOTO";
        vehiculo.add(new Moto(0, placa, color, tipovehiculo, rol));
      
        if (!daoV.existeVehiculo(placa)) {
        vehiculos.add(new Moto(0, placa, color, tipovehiculo, rol));
        }
        
        }
        if (rbtnCarro.isSelected()) {
        tipovehiculo = "CARRO";
        vehiculo.add(new Carro(0, placa, color, tipovehiculo, rol));
        
            if (!daoV.existeVehiculo(placa)) {
            vehiculos.add(new Carro(0, placa, color, tipovehiculo, rol));
            }
        }
        
        gestion.limpiarVehiculo(this, tablaVehiculos, txtPlaca, txtColor, txtRol, tipoVehiculo);
        gestion.agregarVehiculo(tablaVehiculos, vehiculo); 
        
        vehiculoMinimo = true;
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ArrayList<Integer> idsV = new ArrayList<>();
        if (!vehiculoMinimo) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese al menos un vehiculo");
            return;
        }
        
         int respuesta = JOptionPane.showConfirmDialog(
            null,
            "Esta seguro de guardar los datos?",
            "Confirmar Guardado", 
            JOptionPane.YES_NO_OPTION 
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            int idU = daoU.obtenerId(carnet);
            if (vehiculos.size()>=1) {
                daoV.insertarV(vehiculos);
            }
            idsV = daoV.obtenerIdsv(vehiculo);
            daoUV.asociarUsuarioVehiculos(idU, vehiculo , idsV);
            gestion.limpiarVehiculo(this, tablaVehiculos, txtPlaca, txtColor, txtRol, tipoVehiculo);
            vehiculo.clear();
            JOptionPane.showMessageDialog(this, "Se guardo correctamente");
            return;
        } else if (respuesta == JOptionPane.NO_OPTION) {
            return;  
        } else if (respuesta == JOptionPane.CLOSED_OPTION) {
            return;
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusLost
       String placa = txtPlaca.getText().toUpperCase().trim();
       if (!placa.isEmpty()) {
           if (daoV.existeVehiculo(placa)) {
               gestion.agregarDatosDeVehiculoAutomatico(txtColor, rbtnMoto, rbtnCarro, daoV.obtenerVehiculoPorPlaca(placa));
            }  
        } 
    }//GEN-LAST:event_txtPlacaFocusLost

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
       String placa = txtPlaca.getText().toUpperCase().trim();
       if (!placa.isEmpty()) {
           if (daoV.existeVehiculo(placa)) {
               gestion.agregarDatosDeVehiculoAutomatico(txtColor, rbtnMoto, rbtnCarro, daoV.obtenerVehiculoPorPlaca(placa));
            }  
        } 
    }//GEN-LAST:event_txtPlacaActionPerformed

    private boolean validarCamposv(){
        if (txtPlaca.getText().trim().isEmpty()){
           return false; 
        } 
        if (txtColor.getText().trim().isEmpty()){
            return false;
        }
        if (txtRol.getSelectedIndex() == 0) {
            return false;
        }
        if (!rbtnMoto.isSelected() && !rbtnCarro.isSelected()){
            return false;
        }
    return true;
    }
    
    public JTable getTablaUsuario(){
        return tablaUsuario;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Vehiculo dialog = new Vehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtnCarro;
    private javax.swing.JRadioButton rbtnMoto;
    private javax.swing.JTable tablaUsuario;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.ButtonGroup tipoVehiculo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JComboBox<String> txtRol;
    // End of variables declaration//GEN-END:variables
}
